check50:
  checks:
    hello world:
    - run: python3 hello.py # run python3 hello.py
      stdout: Hello, world! # expect Hello, world! in stdout
      stdin: 
        - "bruce"
        - "joe"
      stdout: 
        - "bruce"
        - "joe"
