check50:
  checks:
    hello world:
    - run: python3 hello.py
      stdout: "Hello, world!"
    - run: python3 hello.py # run python3 hello.py
      stdin: 
        - "bruce"
        - "joe"
      stdout: 
        - "bruce"
        - "joe"
