check50:
  checks:
    hello world:
    - run: python3 hello.py # run python3 hello.py
      stdout: Hello, world! # expect Hello, world! in stdout
      exit: 0 # expect program to exit with exitcode 0
    bar:
    - run: python3 hello.py
      stdin: "bruce"
      stdout: "bruce"
      exit: 0
