check50:
  checks:
    hello world:
    - run: python3 hello.py # run python3 hello.py
      stdin: 
        - "bruce"
        - "joe"
      stdout: 
        - "Hello, world!"
        - "bruce"
        - "joe"
